Revert "soong: cc: Enable global O3"
We might need a newer compiler for this.
It looks like O3 is causing:

[ 32% 44439/137026] //system/libbase:libbase header-abi-diff libbase.so.abidiff
FAILED: out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm64_armv8-2a_shared/libbase.so.abidiff
(prebuilts/clang-tools/linux-x86/bin/header-abi-diff -target-version current -allow-unreferenced-changes -allow-unreferenced-elf-symbol-changes -lib libbase -arch arm64 -o out/soong/.intermediates/system/libbase/libbase/android_vendor.34_a
rm64_armv8-2a_shared/libbase.so.abidiff -new out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm64_armv8-2a_shared/libbase.so.lsdump -old prebuilts/abi-dumps/vndk/34/64/arm64/source-based/libbase.so.lsdump)|| (echo 'error
: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libbase' && (mkdir -p $DIST_DIR/abidiffs && cp out/soong/.intermediates/system/libbase/libbase/android_vendor.
34_arm64_armv8-2a_shared/libbase.so.abidiff $DIST_DIR/abidiffs/) && exit 1)
******************************************************
error: libbase's ABI has INCOMPATIBLE CHANGES. Please check compatibility report at: out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm64_armv8-2a_shared/libbase.so.abidiff
******************************************************
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libbase
[ 32% 44441/137026] //system/libbase:libbase header-abi-diff libbase.so.abidiff [arm]
FAILED: out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm_armv8-a_shared/libbase.so.abidiff
(prebuilts/clang-tools/linux-x86/bin/header-abi-diff -target-version current -allow-unreferenced-changes -allow-unreferenced-elf-symbol-changes -lib libbase -arch arm -o out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm
_armv8-a_shared/libbase.so.abidiff -new out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm_armv8-a_shared/libbase.so.lsdump -old prebuilts/abi-dumps/vndk/34/64/arm_arm64/source-based/libbase.so.lsdump)|| (echo 'error: Pl
ease update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libbase' && (mkdir -p $DIST_DIR/abidiffs && cp out/soong/.intermediates/system/libbase/libbase/android_vendor.34_a
rm_armv8-a_shared/libbase.so.abidiff $DIST_DIR/abidiffs/) && exit 1)
******************************************************
error: libbase's ABI has INCOMPATIBLE CHANGES. Please check compatibility report at: out/soong/.intermediates/system/libbase/libbase/android_vendor.34_arm_armv8-a_shared/libbase.so.abidiff
******************************************************
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libbase
12:35:33 ninja failed with: exit status 1

This reverts commit 2f9f0e6eb45126e792e7f170786384ecaa47ea6f.